// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rep/rep/likes_record.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LikesRecord struct {
	Liker string `protobuf:"bytes,1,opt,name=liker,proto3" json:"liker,omitempty"`
	Liked uint64 `protobuf:"varint,2,opt,name=liked,proto3" json:"liked,omitempty"`
}

func (m *LikesRecord) Reset()         { *m = LikesRecord{} }
func (m *LikesRecord) String() string { return proto.CompactTextString(m) }
func (*LikesRecord) ProtoMessage()    {}
func (*LikesRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cf0566bad8980a2, []int{0}
}
func (m *LikesRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LikesRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LikesRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LikesRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikesRecord.Merge(m, src)
}
func (m *LikesRecord) XXX_Size() int {
	return m.Size()
}
func (m *LikesRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_LikesRecord.DiscardUnknown(m)
}

var xxx_messageInfo_LikesRecord proto.InternalMessageInfo

func (m *LikesRecord) GetLiker() string {
	if m != nil {
		return m.Liker
	}
	return ""
}

func (m *LikesRecord) GetLiked() uint64 {
	if m != nil {
		return m.Liked
	}
	return 0
}

func init() {
	proto.RegisterType((*LikesRecord)(nil), "rep.rep.LikesRecord")
}

func init() { proto.RegisterFile("rep/rep/likes_record.proto", fileDescriptor_0cf0566bad8980a2) }

var fileDescriptor_0cf0566bad8980a2 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x4a, 0x2d, 0xd0,
	0x07, 0xe1, 0x9c, 0xcc, 0xec, 0xd4, 0xe2, 0xf8, 0xa2, 0xd4, 0xe4, 0xfc, 0xa2, 0x14, 0xbd, 0x82,
	0xa2, 0xfc, 0x92, 0x7c, 0x21, 0xf6, 0xa2, 0xd4, 0x02, 0xbd, 0xa2, 0xd4, 0x02, 0x25, 0x4b, 0x2e,
	0x6e, 0x1f, 0x90, 0x74, 0x10, 0x58, 0x56, 0x48, 0x84, 0x8b, 0x15, 0xa4, 0xba, 0x48, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x33, 0x08, 0xc2, 0x81, 0x89, 0xa6, 0x48, 0x30, 0x29, 0x30, 0x6a, 0xb0, 0x40,
	0x44, 0x53, 0x9c, 0x34, 0x4f, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39,
	0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0x8a, 0x1f,
	0x64, 0x6b, 0x05, 0xd8, 0xee, 0x92, 0xca, 0x82, 0xd4, 0xe2, 0x24, 0x36, 0xb0, 0xad, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x46, 0x86, 0xcf, 0x09, 0x93, 0x00, 0x00, 0x00,
}

func (m *LikesRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LikesRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LikesRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Liked != 0 {
		i = encodeVarintLikesRecord(dAtA, i, uint64(m.Liked))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Liker) > 0 {
		i -= len(m.Liker)
		copy(dAtA[i:], m.Liker)
		i = encodeVarintLikesRecord(dAtA, i, uint64(len(m.Liker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLikesRecord(dAtA []byte, offset int, v uint64) int {
	offset -= sovLikesRecord(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LikesRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Liker)
	if l > 0 {
		n += 1 + l + sovLikesRecord(uint64(l))
	}
	if m.Liked != 0 {
		n += 1 + sovLikesRecord(uint64(m.Liked))
	}
	return n
}

func sovLikesRecord(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLikesRecord(x uint64) (n int) {
	return sovLikesRecord(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LikesRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLikesRecord
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LikesRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LikesRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Liker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLikesRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLikesRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLikesRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Liker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Liked", wireType)
			}
			m.Liked = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLikesRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Liked |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLikesRecord(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLikesRecord
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLikesRecord(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLikesRecord
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLikesRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLikesRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLikesRecord
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLikesRecord
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLikesRecord
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLikesRecord        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLikesRecord          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLikesRecord = fmt.Errorf("proto: unexpected end of group")
)
